import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';
import { chromium } from 'playwright';
const bundle = await build({ entryPoints: ['tests/helpers/card-fixture.mjs'], bundle: true, write: false, format: 'esm', external: ['electron', 'node:child_process'], alias: { obsidian: resolve('tests/helpers/obsidian-browser.mjs') } });
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL, headless: true });
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=', 'base64');
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); page.setDefaultTimeout(4000);
  await page.route('https://tracelo.test/', route => route.fulfill({ contentType: 'text/html', body: '<style>' + readFileSync('tests/helpers/obsidian-host.css', 'utf8') + readFileSync('styles.css', 'utf8') + '</style><script type="module">' + bundle.outputFiles[0].text + '</script>' }));
  await page.goto('https://tracelo.test/'); await page.waitForFunction(() => window.cardFixture);
  const originalCount = await page.evaluate(() => window.cardFixture.plugin.tasks.length);
  const open = () => page.getByRole('button', { name: '新建任务', exact: true }).click();
  await open(); const modal = page.locator('.wt-new-task-modal');
  await modal.locator('#task-title').fill('带图创建');
  await modal.locator('#task-details').fill('前文后文');
  await modal.locator('#task-details').evaluate(el => { el.focus(); el.setSelectionRange(2,2); });
  await modal.locator('input[type=file]').setInputFiles([{ name: 'one.png', mimeType: 'image/png', buffer: png }, { name: 'two.png', mimeType: 'image/png', buffer: png }]);
  await modal.locator('.wt-draft-image').nth(1).waitFor();
  await page.waitForFunction(() => !document.querySelector('#submit').disabled);
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.tasks.length), originalCount, 'pasting must not create a task');
  const notes = await modal.locator('#task-details').inputValue();
  assert.match(notes, /^前文\n!\[one.png\]/); assert.match(notes, /two.png[\s\S]*后文$/);
  await modal.getByRole('button', { name: '移除图片：one.png' }).click();
  assert.equal(await modal.locator('.wt-draft-image').count(), 1);
  await modal.getByRole('button', { name: '撤销移除图片' }).click();
  assert.equal(await modal.locator('.wt-draft-image').count(), 2);
  await modal.getByRole('button', { name: '清空草稿', exact: true }).click();
  assert.equal(await modal.locator('.wt-draft-image').count(), 0);
  await modal.getByRole('button', { name: '撤销清空草稿', exact: true }).click();
  assert.equal(await modal.locator('.wt-draft-image').count(), 2);
  await modal.getByRole('button', { name: '取消', exact: true }).click(); await open();
  assert.equal(await modal.locator('.wt-draft-image').count(), 2);
  await modal.getByRole('button', { name: '取消', exact: true }).click();
  await page.evaluate(() => { window.originalDirectory = window.cardFixture.plugin.state.taskDirectory; window.cardFixture.plugin.state.taskDirectory = '另一任务目录'; });
  await open(); assert.equal(await modal.locator('.wt-draft-image').count(), 0);
  assert.equal(await modal.locator('#task-title').inputValue(), '');
  await modal.getByRole('button', { name: '取消', exact: true }).click();
  await page.evaluate(() => { window.cardFixture.plugin.state.taskDirectory = window.originalDirectory; });
  await open(); assert.equal(await modal.locator('.wt-draft-image').count(), 2);
  await page.evaluate(() => { const a = window.cardFixture.app.vault.adapter; window.restoreImages = a.writeBinary.bind(a); a.writeBinary = async () => { throw Error('模拟附件写入失败'); }; });
  await modal.getByRole('button', { name: '创建任务', exact: true }).click();
  await modal.getByRole('alert').filter({ hasText: '模拟附件写入失败' }).waitFor();
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.tasks.length), originalCount);
  assert.equal(await modal.locator('.wt-draft-image').count(), 2);
  await page.evaluate(() => { window.cardFixture.app.vault.adapter.writeBinary = window.restoreImages; });
  await modal.getByRole('button', { name: '创建任务', exact: true }).click(); await modal.waitFor({ state: 'detached' });
  const result = await page.evaluate(async () => { const {plugin,app} = window.cardFixture; const tasks = plugin.tasks.filter(t => t.title === '带图创建'); const task = tasks[0]; return { count: tasks.length, task, files: await app.vault.adapter.list(task.materialFolder), source: await app.vault.adapter.read(plugin.taskArchivePath(task.id)) }; });
  assert.equal(result.count, 1); assert.doesNotMatch(result.task.notes, /tracelo-draft:|data:image/); assert.equal(result.files.files.filter(f => f.endsWith('.png')).length, 2);
  assert.match(result.source, /one.png/);
  await open(); await modal.locator('#task-title').fill('异步图片草稿');
  await page.evaluate(() => {
    const original = FileReader.prototype.readAsDataURL;
    window.pendingImageReads = [];
    window.restoreReader = () => { FileReader.prototype.readAsDataURL = original; };
    FileReader.prototype.readAsDataURL = function(file) { window.pendingImageReads.push(() => original.call(this, file)); };
  });
  await modal.locator('input[type=file]').setInputFiles({ name: 'late.png', mimeType: 'image/png', buffer: png });
  assert.equal(await modal.locator('#submit').isDisabled(), true);
  await modal.getByRole('button', { name: '清空草稿', exact: true }).click();
  await modal.locator('#task-title').fill('清空后新内容');
  await page.evaluate(() => { window.restoreReader(); for (const read of window.pendingImageReads) read(); });
  await page.waitForFunction(() => !document.querySelector('#submit').disabled);
  assert.equal(await modal.locator('.wt-draft-image').count(), 0);
  assert.equal(await modal.locator('#task-title').inputValue(), '清空后新内容');
  await modal.getByRole('button', { name: '撤销清空草稿', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('#submit').disabled);
  assert.equal(await modal.locator('.wt-draft-image').count(), 1);
  await modal.getByRole('button', { name: '预览图片：late.png' }).click();
  await page.keyboard.press('Escape');
  assert.equal(await modal.count(), 1);
  assert.equal(await modal.getByRole('button', { name: '预览图片：late.png' }).evaluate(el => el === document.activeElement), true);
  await modal.getByRole('button', { name: '取消', exact: true }).click();
  await open(); assert.equal(await modal.locator('.wt-draft-image').count(), 1);
  await modal.getByRole('button', { name: '清空草稿', exact: true }).click();
  await modal.locator('#task-title').fill('混合剪贴板');
  await modal.locator('#task-details').evaluate((el, base64) => {
    el.focus(); const clipboard = new DataTransfer();
    clipboard.items.add(new File([Uint8Array.from(atob(base64), c => c.charCodeAt(0))], 'paste.png', { type: 'image/png' }));
    clipboard.setData('text/plain', '混合文字'); clipboard.setData('text/html', '<p>混合文字<img src="file:///clipboard.png"></p>');
    el.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, clipboardData: clipboard }));
  }, png.toString('base64'));
  await page.waitForFunction(() => !document.querySelector('#submit').disabled);
  assert.equal(await modal.locator('.wt-draft-image').count(), 1);
  assert.match(await modal.locator('#task-details').inputValue(), /混合文字/);
  console.log('PASS delayed image clear/undo, preview Escape and mixed clipboard deduplication');
  console.log('PASS image drafts: multi-select, insertion, remove/undo, clear/undo, reopen, attachment failure and atomic creation');
} finally { await browser.close(); }
