import assert from 'node:assert/strict';
import { readFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';
import { chromium } from 'playwright';

const bundle = await build({ entryPoints: ['tests/helpers/card-fixture.mjs'], bundle: true, write: false, format: 'esm', external: ['electron', 'node:child_process'], alias: { obsidian: resolve('tests/helpers/obsidian-browser.mjs') } });
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL, headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, reducedMotion: 'reduce' });
  page.setDefaultTimeout(5000);
  await page.addInitScript(()=>{window.fixtureModalHeaderWrapper=true;});
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.route('https://tracelo.test/', route => route.fulfill({ contentType: 'text/html', body: '<style>' + readFileSync('tests/helpers/obsidian-host.css', 'utf8') + readFileSync('styles.css', 'utf8') + '</style><script type="module">' + bundle.outputFiles[0].text + '</script>' }));
  await page.goto('https://tracelo.test/');
  await page.waitForFunction(() => window.cardFixture);
  assert.equal(await page.getByRole('button', { name: '一句话', exact: true }).count(), 0, 'one-sentence capture belongs inside task creation');
  await page.evaluate(() => {
    window.require = name => {
      if (name !== 'fs') throw Error('unexpected module');
      return { promises: { readFile: async () => 'sk-' + 'x'.repeat(32) } };
    };
    window.cardFixture.plugin.state.smartCapture = { baseUrl: 'https://api.kimi.com/coding/v1', model: 'kimi-for-coding', keyFile: '/tmp/test-key.md' };
    window.modelCalls = 0;
    window.modelRequest = async request => {
      window.modelCalls++;
      window.lastModelBody = JSON.parse(request.body);
      if (window.modelFailure) return { status: 503, text: 'private provider error' };
      if (window.pauseModel) await new Promise(resolve => { window.releaseModel = resolve; });
      if (JSON.parse(request.body).messages.at(-1).content.includes('名为连接测试')) return { status: 200, text: JSON.stringify({ choices: [{ finish_reason: 'stop', message: { content: JSON.stringify({ title: '连接测试', notes: '', groupId: null, important: null, urgent: null, dueDate: null, todos: [], initialProgress: '', warnings: [] }) } }] }) };
      const content = window.progressMode ? { text: '退款验证已完成，准备验收', completedTodoIds: [window.cardFixture.plugin.tasks[0].todos[2].id], warnings: [] }
        : { title: '排查相机启动慢', notes: '保留启动耗时日志', groupId: window.cardFixture.plugin.groups[0].id, important: true, urgent: true, dueDate: '2026-10-05', todos: ['抓日志', '分析耗时'], initialProgress: '已复现问题', warnings: [] };
      return { status: 200, text: JSON.stringify({ choices: [{ finish_reason: 'stop', message: { content: JSON.stringify(content) } }] }) };
    };
  });
  const open = async () => {
    if (!await page.locator('.wt-capture-dialog').count()) await page.locator('.wt-new-task-button').click();
    await page.getByRole('button', { name: '一句话整理', exact: true }).click();
  };
  const modal = page.locator('.wt-smart-modal');
  const raw = modal.getByRole('textbox', { name: '说说要做的事', exact: true, includeHidden: true });
  await page.locator('.wt-new-task-button').click();
  await page.getByRole('textbox',{name:'任务名称',exact:true}).fill('手动填写草稿');
  await open();
  assert.equal(await modal.locator('.modal-title').isVisible(),false,'embedded capture has no second modal heading, including the real host header wrapper');
  assert.deepEqual(await page.locator('.wt-capture-tabs button').allTextContents(),['新建任务','记录进展']);
  await raw.fill('一句话草稿');
  await raw.dispatchEvent('compositionstart');
  await page.getByRole('button',{name:'手动填写',exact:true}).click();
  assert.equal(await raw.isVisible(),true,'method switch preserves the composing node');
  await raw.dispatchEvent('compositionend');
  await page.getByRole('button',{name:'手动填写',exact:true}).click();
  await modal.waitFor({state:'detached'});
  assert.equal(await page.getByRole('textbox',{name:'任务名称',exact:true}).inputValue(),'手动填写草稿');
  await open();
  assert.equal(await raw.inputValue(),'一句话草稿');
  await raw.fill('明天排查相机启动慢，先抓日志，再分析耗时，已经复现。');
  await page.evaluate(() => { window.modelFailure = true; });
  await modal.getByRole('button', { name: '整理成任务', exact: true }).click();
  await modal.getByRole('alert').filter({ hasText: '503' }).waitFor();
  assert.match(await raw.inputValue(), /启动慢/);
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.tasks.length), 4);
  await modal.getByRole('button', { name: '关闭', exact: true }).click();
  await open();
  assert.match(await raw.inputValue(), /启动慢/, 'raw draft restored');
  await page.evaluate(() => { window.modelFailure = false; window.pauseModel = true; });
  await modal.getByRole('button', { name: '整理成任务', exact: true }).click();
  await page.waitForFunction(() => window.releaseModel);
  await modal.getByRole('button', { name: '取消整理', exact: true }).click();
  await page.evaluate(() => { window.pauseModel = false; window.releaseModel(); });
  assert.equal(await modal.locator('#task-title').count(), 0, 'cancelled response cannot populate preview');
  await modal.getByRole('button', { name: '整理成任务', exact: true }).click();
  await modal.locator('#task-title').waitFor();
  assert.equal(await modal.locator('#task-title').inputValue(), '排查相机启动慢');
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.tasks.length), 4, 'extraction alone does not save');
  await modal.locator('#task-title').fill('确认后的相机任务');
  await modal.getByRole('button', { name: '取消', exact: true }).click();
  await open();
  assert.equal(await modal.locator('#task-title').inputValue(), '确认后的相机任务', 'edited preview survives close');
  assert.equal(await raw.isVisible(),false,'confirmation replaces the input stage');
  await modal.getByRole('button',{name:'返回原文',exact:true}).click();
  await raw.fill('补充：下周继续排查相机');
  assert.equal(await modal.locator('#task-title').inputValue(), '确认后的相机任务', 'changing source preserves edited preview');
  await modal.getByRole('button', { name: '整理成任务', exact: true }).click();
  await modal.getByRole('button', { name: '保留当前结果', exact: true }).click();
  assert.equal(await modal.locator('#task-title').inputValue(), '确认后的相机任务');
  await modal.getByRole('button', { name:'整理成任务', exact:true }).click();
  await modal.getByRole('button', { name:'替换并重新整理', exact:true }).click();
  await page.waitForFunction(()=>document.querySelector('.wt-smart-modal #task-title')?.value==='排查相机启动慢');
  await modal.getByRole('button',{name:'返回原文',exact:true}).click();
  await modal.getByRole('button', {name:'恢复上一版结果',exact:true}).click();
  assert.equal(await modal.locator('#task-title').inputValue(),'确认后的相机任务','re-extraction retains a recoverable edited version');
  await page.evaluate(() => {
    const adapter = window.cardFixture.app.vault.adapter, original = adapter.write;
    window.restoreSmartWrite = () => { adapter.write = original; };
    adapter.write = async () => { throw Error('模拟写入失败'); };
  });
  await modal.getByRole('button', { name: '创建任务', exact: true }).click();
  await modal.getByRole('alert').filter({ hasText: '模拟写入失败' }).waitFor();
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.tasks.length), 4);
  await page.evaluate(() => window.restoreSmartWrite());
  mkdirSync('test-results/smart-capture', { recursive: true });
  await page.screenshot({ path: 'test-results/smart-capture/create-preview.png' });
  await modal.getByRole('button', { name: '创建任务', exact: true }).click();
  await modal.waitFor({ state: 'detached' });
  const created = await page.evaluate(() => window.cardFixture.plugin.tasks.find(t => t.title === '确认后的相机任务'));
  assert.equal(created.todos.length, 2); assert.equal(created.dueDate, '2026-10-05');
  assert.equal(created.events.filter(e => e.kind === 'progress').length, 1);
  console.log('PASS create preview, editing, draft recovery, failure and cancellation');

  await page.evaluate(() => { window.progressMode = true; window.cardFixture.plugin.openSmartCapture(window.cardFixture.ids.payment); });
  await raw.fill('退款与异常流程验证完成，准备验收');
  await modal.getByRole('button', { name: '整理进展', exact: true }).click();
  const progress = modal.getByRole('textbox', { name: '整理后的进展', exact: true });
  await progress.waitFor();
  await progress.fill('人工确认：退款与异常流程已验证');
  await page.screenshot({ path: 'test-results/smart-capture/progress-preview.png' });
  await page.evaluate(() => {
    const plugin = window.cardFixture.plugin, original = plugin.saveSmartProgress.bind(plugin);
    window.progressSaves = 0;
    plugin.saveSmartProgress = async (...args) => { window.progressSaves++; await new Promise(resolve => { window.releaseSave = resolve; }); return original(...args); };
  });
  await modal.getByRole('button', { name: '保存进展', exact: true }).click();
  await modal.locator('.wt-smart-progress-form').evaluate(form => { form.requestSubmit(); form.requestSubmit(); });
  assert.equal(await page.evaluate(() => window.progressSaves), 1);
  await page.evaluate(() => window.releaseSave());
  await modal.waitFor({ state: 'detached' });
  const updated = await page.evaluate(() => window.cardFixture.plugin.tasks.find(t => t.id === window.cardFixture.ids.payment));
  assert.equal(updated.todos[2].done, true);
  assert.equal(updated.events.at(-1).text, '人工确认：退款与异常流程已验证');
  assert.equal(updated.events.filter(e => e.text === '人工确认：退款与异常流程已验证').length, 1);
  console.log('PASS selected task progress, todo completion and duplicate-submit protection');

  await open();
  await raw.fill('保留这条原文');
  await page.evaluate(()=>{
    const plugin=window.cardFixture.plugin, save=plugin.saveData.bind(plugin);
    window.restoreDraftSave=()=>{plugin.saveData=save;};
    plugin.saveData=async()=>{throw Error('模拟草稿写入失败');};
  });
  await page.getByRole('button',{name:'手动填写',exact:true}).click();
  await modal.getByRole('alert').filter({hasText:'草稿'}).waitFor();
  assert.equal(await raw.inputValue(),'保留这条原文','failed draft flush keeps the editor open');
  await page.evaluate(()=>window.restoreDraftSave());
  await modal.getByRole('button', { name: '模型设置', exact: true }).click();
  const settings = page.locator('.wt-smart-settings');
  await settings.getByLabel('API Key', {exact:true}).fill('test-direct-token-1234567890');
  assert.equal(await settings.getByLabel('API Key', {exact:true}).getAttribute('type'),'password');
  await page.evaluate(() => { window.require = () => { throw Error('direct keys must not read a file'); }; });
  await settings.getByRole('button', { name: '测试连接', exact: true }).click();
  await settings.getByRole('status').filter({ hasText: '连接成功' }).waitFor();
  assert.equal(await page.evaluate(() => window.lastModelBody.messages.at(-1).content.includes('保留这条原文')), false, 'connection test never sends draft');
  await settings.getByRole('textbox', { name: '服务地址', exact: true }).fill('http://unsafe.test');
  await settings.getByRole('button', { name: '保存设置', exact: true }).click();
  await settings.getByRole('alert').filter({ hasText: 'HTTPS' }).waitFor();
  await settings.getByRole('textbox', { name: '服务地址', exact: true }).fill('https://api.kimi.com/coding/v1');
  await settings.getByRole('button', { name: '保存设置', exact: true }).click();
  await settings.waitFor({ state: 'detached' });
  assert.equal(await page.evaluate(() => JSON.stringify(window.cardFixture.plugin.data).includes('sk-' + 'x'.repeat(32))), false);
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.data.smartCapture.apiKey), 'test-direct-token-1234567890');
  assert.equal(await page.evaluate(() => window.cardFixture.plugin.data.smartCapture.keyFile), '');
  await page.evaluate(() => { window.progressMode = false; });
  await modal.getByRole('button', { name: '整理成任务', exact: true }).click();
  await modal.locator('#task-title').waitFor();
  for (const [width, height] of [[800, 500], [390, 700]]) {
    await page.setViewportSize({ width, height });
    assert.equal(await modal.evaluate(el => el.scrollWidth <= el.clientWidth + 1 && el.getBoundingClientRect().bottom <= innerHeight), true);
    assert.equal(await modal.getByRole('button', { name: '创建任务', exact: true }).evaluate(el => el.getBoundingClientRect().bottom <= innerHeight), true);
  }
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.evaluate(() => { window.cardFixture.plugin.state.appearance = 'dark'; window.cardFixture.plugin.applyAppearance(); });
  await page.screenshot({ path: 'test-results/smart-capture/dark-preview.png' });
  await modal.getByRole('button',{name:'返回原文',exact:true}).click();
  await page.evaluate(()=>{
    const plugin=window.cardFixture.plugin, save=plugin.saveData.bind(plugin);
    window.restoreDiscardSave=()=>{plugin.saveData=save;};
    plugin.saveData=async()=>{throw Error('模拟草稿删除失败');};
  });
  await modal.getByRole('button', { name: '放弃草稿', exact: true }).click();
  await modal.getByRole('button', { name: '确认放弃', exact: true }).click();
  await modal.getByRole('alert').filter({hasText:'未能清除磁盘上的草稿'}).waitFor();
  assert.equal(await raw.inputValue(),'保留这条原文');
  assert.equal(await modal.locator('#task-title').count(),1);
  await page.evaluate(()=>window.restoreDiscardSave());
  await modal.getByRole('button', { name: '放弃草稿', exact: true }).click();
  await modal.getByRole('button', { name: '确认放弃', exact: true }).click();
  await modal.getByRole('status').filter({hasText:'草稿已放弃'}).waitFor();
  assert.equal(await raw.inputValue(), '');
  assert.equal(await modal.locator('#task-title').count(), 0);
  await modal.getByRole('button', { name: '关闭', exact: true }).click();
  await open();
  assert.equal(await raw.inputValue(), '', 'discard is persisted');
  assert.deepEqual(errors, []);
  console.log('PASS narrow layout and no uncaught browser errors');
} finally { await browser.close(); }
