import assert from 'node:assert/strict';
import {readFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const bundle=await build({entryPoints:['tests/helpers/card-fixture.mjs'],bundle:true,write:false,format:'esm',external:['electron','node:child_process'],alias:{obsidian:resolve('tests/helpers/obsidian-browser.mjs')}});
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.setDefaultTimeout(6000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://tracelo.test/',r=>r.fulfill({contentType:'text/html',body:'<style>'+readFileSync('tests/helpers/obsidian-host.css','utf8')+readFileSync('styles.css','utf8')+'</style><script type="module">'+bundle.outputFiles[0].text+'</script>'}));
 await page.goto('https://tracelo.test/');await page.waitForFunction(()=>window.cardFixture);
 assert.equal(await page.locator('.wt-conversation').count(),1,'conversation replaces only the event area');
 assert.equal(await page.locator('.wt-week button').count(),7);
 assert.equal(await page.locator('.wt-date-controls').count(),1);
 await page.evaluate(()=>{
  const p=window.cardFixture.plugin;p.state.smartCapture={baseUrl:'https://example.test',model:'test',apiKey:'sk-'+'x'.repeat(24)};
  window.modelRequest=async request=>{
   window.lastChatRequest=JSON.parse(request.body);
   if(window.pauseChat)await new Promise(r=>window.releaseChat=r);
   if(window.failChat)return{status:503,text:'private server error'};
   const t=p.tasks[0];
   const proposal=window.chatCreate?{type:'create',values:{title:'对话创建',notes:'',groupId:null,important:null,urgent:null,dueDate:null,todos:['验证'],initialProgress:'',warnings:[]}}:window.chatUpdate?{type:'update',taskId:t.id,actions:[{kind:'progress',text:'日志已采集完成'},{kind:'due',text:'2026-10-09'}]}:null;
   return{status:200,text:JSON.stringify({choices:[{message:{content:JSON.stringify({reply:'先对比初始化各阶段的耗时。',proposal})}}]})};
  };
 });
 const chat=page.locator('.wt-conversation'),input=chat.getByRole('textbox',{name:'对话内容'});
 await input.fill('先整理一下思路');await chat.getByRole('button',{name:'发送',exact:true}).click();
 await chat.getByText('先对比初始化各阶段的耗时。',{exact:true}).waitFor();
 assert.equal(await chat.locator('.wt-chat-proposal').count(),0);
 await chat.getByRole('button',{name:'@ 卡片',exact:true}).click();
 await chat.locator('.wt-chat-picker button').first().click();
 await page.evaluate(()=>window.chatUpdate=true);
 await input.fill('记一下进展，截止改到周五');await chat.getByRole('button',{name:'发送',exact:true}).click();
 await chat.getByRole('button',{name:'确认应用',exact:true}).waitFor();
 mkdirSync('test-results/work-conversation-live',{recursive:true});
 await page.screenshot({path:'test-results/work-conversation-live/proposal.png'});
 const before=await page.evaluate(()=>window.cardFixture.plugin.tasks[0].events.length);
 await page.evaluate(()=>{const store=window.cardFixture.plugin.store;window.chatSave=store.saveTask.bind(store);store.saveTask=async()=>{throw Error('测试写盘失败');};});
 await chat.getByRole('button',{name:'确认应用',exact:true}).click();await chat.getByRole('alert').filter({hasText:'测试写盘失败'}).waitFor();
 assert.equal(await page.evaluate(()=>window.cardFixture.plugin.tasks[0].events.length),before);
 await page.evaluate(()=>window.cardFixture.plugin.store.saveTask=window.chatSave);
 await page.evaluate(async()=>{const view=window.cardFixture.app.workspace.getLeavesOfType('work-timeline-view')[0].view;await view.onClose();view.conversation=undefined;await view.onOpen();});
 assert.equal(await chat.getByRole('button',{name:'确认应用',exact:true}).isVisible(),true,'pending operation survives closing the view');
 await input.fill('未发送草稿');
 await page.locator('.wt-card-open').first().click();
 assert.equal(await input.inputValue(),'未发送草稿');assert.equal(await chat.isVisible(),true,'card expansion does not switch away from chat');
 await chat.getByRole('button',{name:'确认应用',exact:true}).click();
 await chat.getByText('已更新任务',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>window.cardFixture.plugin.tasks[0].dueDate),'2026-10-09');
 assert.equal(await page.evaluate(()=>window.cardFixture.plugin.tasks[0].events.length),before+2);
 const disk=await page.evaluate(()=>{const p=window.cardFixture.plugin;return window.cardFixture.app.vault.adapter.read(p.taskArchivePath(p.tasks[0].id));});assert.ok(disk.includes('日志已采集完成')&&disk.includes('2026-10-09'));
 await chat.getByRole('button',{name:'新对话',exact:true}).click();
 assert.equal(await input.inputValue(),'');
 await chat.getByRole('combobox',{name:'选择会话'}).selectOption({index:1});
 assert.equal(await input.inputValue(),'未发送草稿');
 await input.dispatchEvent('compositionstart');await input.dispatchEvent('keydown',{key:'Enter',metaKey:true,isComposing:true});assert.equal(await input.inputValue(),'未发送草稿');await input.dispatchEvent('compositionend');
 await page.getByRole('button',{name:'活动记录',exact:true}).click();
 assert.equal(await chat.isVisible(),false);await page.getByRole('button',{name:'返回对话',exact:true}).click();assert.equal(await input.inputValue(),'未发送草稿');
 await page.evaluate(()=>{window.chatUpdate=false;window.chatCreate=true;});await input.fill('新建分析任务');await chat.getByRole('button',{name:'发送',exact:true}).click();
 await chat.getByRole('button',{name:'确认创建',exact:true}).waitFor();
 await chat.getByRole('button',{name:'修改内容',exact:true}).click();await chat.locator('#task-title').fill('对话创建（人工修订）');
 await chat.getByRole('button',{name:'取消',exact:true}).click();
 await chat.getByRole('button',{name:'确认创建',exact:true}).click();
 await chat.getByText('已创建任务',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>window.cardFixture.plugin.tasks.filter(t=>t.title==='对话创建（人工修订）').length),1);
 await page.evaluate(()=>{window.chatCreate=false;window.failChat=true;});await input.fill('失败后保留');await chat.getByRole('button',{name:'发送',exact:true}).click();await chat.getByRole('alert').filter({hasText:'503'}).waitFor();assert.equal(await input.inputValue(),'失败后保留');
 await page.evaluate(()=>{window.failChat=false;window.pauseChat=true;});await chat.getByRole('button',{name:'发送',exact:true}).click();await page.waitForFunction(()=>window.releaseChat);await chat.getByRole('button',{name:'停止',exact:true}).click();await page.evaluate(()=>{window.pauseChat=false;window.releaseChat();});
 await chat.getByRole('button',{name:'新对话',exact:true}).click();
 await input.fill('重开视图恢复');
 await page.evaluate(async()=>{const view=window.cardFixture.app.workspace.getLeavesOfType('work-timeline-view')[0].view;await view.onClose();view.conversation=undefined;await view.onOpen();});
 assert.equal(await input.inputValue(),'重开视图恢复');
 mkdirSync('test-results/work-conversation-live',{recursive:true});
 await page.screenshot({path:'test-results/work-conversation-live/desktop.png'});
 await page.getByLabel('选择时间线日期').fill('2026-09-26');assert.equal(await page.locator('.wt-timeline-due').count(),1);assert.equal(await input.inputValue(),'重开视图恢复');await page.screenshot({path:'test-results/work-conversation-live/due-retained.png'});
 await page.evaluate(()=>window.cardFixture.plugin.setAppearance('monochrome','dark'));await page.screenshot({path:'test-results/work-conversation-live/dark.png'});await page.evaluate(()=>window.cardFixture.plugin.setAppearance('monochrome','light'));
 for(const width of [1024,780,600,390]){await page.setViewportSize({width,height:850});if(width<780)await page.getByRole('button',{name:'工作对话',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`test-results/work-conversation-live/${width}.png`});}
 await page.setViewportSize({width:390,height:650});await chat.getByRole('button',{name:'发送',exact:true}).scrollIntoViewIfNeeded();const sendBounds=await chat.getByRole('button',{name:'发送',exact:true}).boundingBox();assert.ok(sendBounds.y>=0&&sendBounds.y+sendBounds.height<=650);await page.screenshot({path:'test-results/work-conversation-live/short-reachable.png'});
 assert.deepEqual(errors,[]);console.log('conversation: calendar retained, multi-turn, refs, confirmation, create, drafts, history, failure, cancellation and widths passed');
}finally{await browser.close();}
